services:
  - type: web
    name: bcm-transformer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bcm_transformer.app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free